apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zhkg0c4xv-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:f16a6c83630f5a50e4a39c811e6bd2cd0521c165@sha256:753192353e22e6d8c6c98ac667188a4ad98903a7c3e5e19663e510ecf143ef2f
          name: container-image
